name: Build RPMs
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'Build')"
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          make run-docker
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          title: "WiP RPM Build"
          automatic_release_tag: "WiP"
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: |
            RPMS/**/*.rpm
